######################################################################
# Automatically generated by qmake (3.0) sob. lis 11 16:47:22 2017
######################################################################

TEMPLATE = app
TARGET = GriddlersSolver
INCLUDEPATH += .

# Input
HEADERS += board.h field.h fieldgroup.h fieldline.h tests.h
SOURCES += board.cpp field.cpp fieldgroup.cpp fieldline.cpp main.cpp tests.cpp
